language: node_js
node_js:
  - 15
cache:
  directories:
  - node_modules
script:
  - yarn build
  - yarn test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
