on: "push"

name: CI

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8

      - name: Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint and typecheck
        run: pnpm run lint

  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main')
    needs: test
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8

      - name: Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build
        env:
          VITE_APP_PLAYLIST_IGNORE_LIST: ${{ secrets.VITE_APP_PLAYLIST_IGNORE_LIST }}
          VITE_APP_REDIRECT_URI: ${{ secrets.VITE_APP_REDIRECT_URI }}

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          npx --yes gh-pages -d dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
